#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-/etc/dlc-mcp/env}"
if [ ! -f "$ENV_FILE" ]; then
  echo "missing env file: $ENV_FILE" >&2
  exit 1
fi

set -a
. "$ENV_FILE"
set +a

MODE="${DLC_MCP_SYNC_MODE:-auto}"
TODAY="${DLC_MCP_SYNC_TODAY:-$(date +%Y-%m-%d)}"
TOMORROW_DAY="$(date -d "$TODAY +1 day" +%d)"

if [ "$MODE" = "auto" ]; then
  if [ "$TOMORROW_DAY" = "01" ]; then
    MODE="monthly"
  else
    MODE="daily"
  fi
fi

case "$MODE" in
  daily)
    YESTERDAY="$(date -d "$TODAY -1 day" +%Y-%m-%d)"
    export WEDATA_SYNC_TABLE_CATALOG="${DLC_MCP_DAILY_SYNC_TABLE_CATALOG:-1}"
    export WEDATA_SYNC_METADATA="${DLC_MCP_DAILY_SYNC_METADATA:-1}"
    export WEDATA_NEW_ASSET_START="${YESTERDAY}"
    export WEDATA_NEW_ASSET_END="${YESTERDAY}"
    export WEDATA_NEW_ASSET_STRICT="${DLC_MCP_DAILY_NEW_ASSET_STRICT:-1}"
    export WEDATA_METADATA_TABLE_LIMIT="${DLC_MCP_DAILY_METADATA_TABLE_LIMIT:-100000}"
    export WEDATA_SYNC_DATA_SOURCES="${DLC_MCP_DAILY_SYNC_DATA_SOURCES:-0}"
    export WEDATA_SYNC_INSTANCES="${DLC_MCP_DAILY_SYNC_INSTANCES:-1}"
    export WEDATA_SYNC_PARTITIONS="${DLC_MCP_DAILY_SYNC_PARTITIONS:-1}"
    export WEDATA_PARTITION_DATE="$YESTERDAY"
    export WEDATA_INSTANCE_START="${YESTERDAY} 00:00:00"
    export WEDATA_INSTANCE_END="${YESTERDAY} 23:59:59"
    export WEDATA_INSTANCE_KEYWORDS="${DLC_MCP_DAILY_INSTANCE_KEYWORDS:-}"
    echo "== DLC-MCP daily incremental sync for $YESTERDAY =="
    ;;
  monthly)
    export WEDATA_SYNC_TABLE_CATALOG="${DLC_MCP_MONTHLY_SYNC_TABLE_CATALOG:-1}"
    export WEDATA_SYNC_METADATA="${DLC_MCP_MONTHLY_SYNC_METADATA:-1}"
    export WEDATA_METADATA_TABLE_LIMIT="${DLC_MCP_MONTHLY_METADATA_TABLE_LIMIT:-100000}"
    export WEDATA_SYNC_DATA_SOURCES="${DLC_MCP_MONTHLY_SYNC_DATA_SOURCES:-1}"
    export WEDATA_SYNC_INSTANCES="${DLC_MCP_MONTHLY_SYNC_INSTANCES:-1}"
    export WEDATA_SYNC_PARTITIONS="${DLC_MCP_MONTHLY_SYNC_PARTITIONS:-1}"
    unset WEDATA_PARTITION_DATE
    export WEDATA_INSTANCE_LOOKBACK_DAYS="${DLC_MCP_MONTHLY_INSTANCE_LOOKBACK_DAYS:-2}"
    unset WEDATA_INSTANCE_START WEDATA_INSTANCE_END WEDATA_NEW_ASSET_START WEDATA_NEW_ASSET_END WEDATA_NEW_ASSET_STRICT
    echo "== DLC-MCP monthly full calibration for $TODAY =="
    ;;
  *)
    echo "unknown DLC_MCP_SYNC_MODE: $MODE" >&2
    exit 1
    ;;
esac

bash deploy/sync-wedata-once.sh "$ENV_FILE"
